quarkus:
  datasource:
    db-kind: mysql
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    jdbc:
      url: jdbc:mysql://localhost:${MYSQL_PORT:3306}/${MYSQL_DATABASE}
  flyway:
    migrate-at-start: true
    locations: db/migration
  hibernate-orm:
    database:
      generation: none
